### ISSUE TITLE
Compile-time configuration for `statedir`, `libdir, `bindir`, `unitdir`, `persistent`, `package`

### ISSUE THREAD

**Issue by kstep** [systemd-cron/systemd-cron-next#24]

**Comment by a-detiste** [comment]
Other package support `$prefix` et all so they can work in / , /usr, /usr/local or /home/$user/  
Now for a systemd generator, there are only two possible setup possible: with or without '/usr split'.
systemd-cron now mostly follow the ["separate usr is broken" mantra](1) and building the package on Arch or Gentoo almost require no flags; but it requires a lot of flags on [Debian](2).
(and the `sed -i 's|$$(DESTDIR)$$(bindir)|$$(DESTDIR)/usr/bin|' Makefile` there is ugly)

Maybe replacing all these flags with a single `--enable-split-usr` would make configuration easier; and this would made more sense for people already used to package `systemd` itself. http://www.linuxfromscratch.org/lfs/view/systemd/chapter06/systemd.html

@dbent 

Could `confdir` really be something else that `/etc` ?

[1] http://freedesktop.org/wiki/Software/systemd/separate-usr-is-broken/
[2] http://anonscm.debian.org/cgit/collab-maint/systemd-cron.git/tree/debian/rules

**Comment by kstep** [comment]
I close it for now, as build options are accepted by rust build script via features and environment variables and put binaries and generated units/mans/etc into correct output directory.
