### ISSUE TITLE
Install helper units along with generator

### ISSUE THREAD

**Issue by kstep** [systemd-cron/systemd-cron-next#26]

**Comment by raininja** [comment]
its not building all the units. . .install -m644 /home/raijin/build/aur/systemd-crontab-generator/src/systemd-cron-next-master/out/build/units/cron-minutely.timer /home/raijin/build/aur/systemd-crontab-generator/pkg/systemd-crontab-generator/usr/lib/systemd/system
install: cannot stat ‘/home/raijin/build/aur/systemd-crontab-generator/src/systemd-cron-next-master/out/build/units/cron-minutely.timer’: No such file or directory
Makefile:83: recipe for target 'install' failed

**Comment by kstep** [comment]
@raininja It's a known issue. The project is still under development, although I slowed down development process recently due to my day job.

**Comment by kstep** [comment]
@raininja, FYI, 30f02bb commit implemented schedule-specific units generation.

**Comment by raininja** [comment]
thanks for the notice
