### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by raininja** [systemd-cron/systemd-cron-next#27]
cargo build --release
   Compiling rustc-serialize v0.3.15
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 help: run `rustc --explain E0277` to see a detailed explanation
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: `Self` does not have a constant size known at compile-time
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: required by `core::result::Result`
/home/raijin/.cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build failed, waiting for other jobs to finish...
Could not compile `rustc-serializ

**Comment by kstep** [comment]
@raininja What Rust version do you use?

**Comment by raininja** [comment]
[raijin@raimote][~/build/aur/systemd-crontab-generator/src/systemd-cron-next-master]%rustc --version
rustc 1.4.0-nightly (63ba780fd 2015-08-23)

**Comment by raininja** [comment]
looking more closely at this error- it looks to be a rust error and not cron-next?

**Comment by steveklabnik** [comment]
@kstep I've been investigating this on IRC with @raininja . Here's a full output from me:

```
$ cargo build
   Compiling rustlex_codegen v0.3.0
   Compiling strsim v0.3.0
   Compiling winapi v0.2.1
   Compiling md5 v0.1.1
   Compiling cronparse v0.4.0
   Compiling libc v0.1.8
   Compiling regex-syntax v0.2.1
   Compiling rustc-serialize v0.3.15
   Compiling winapi-build v0.1.1
   Compiling glob v0.2.10
   Compiling lazy_static v0.1.14
   Compiling memchr v0.1.3
   Compiling log v0.3.1
   Compiling users v0.4.3
   Compiling winapi v0.1.23
   Compiling advapi32-sys v0.1.2
   Compiling kernel32-sys v0.1.3
   Compiling aho-corasick v0.3.0
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:159:25: 159:40 error: unresolved name `token::get_name` [E0425]
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:159                 let s = token::get_name(id);
                                                                                                                                                         ^~~~~~~~~~~~~~~
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:159:25: 159:40 help: run `rustc --explain E0425` to see a detailed explanation
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:203:35: 203:50 error: unresolved name `token::get_name` [E0425]
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:203             match regex::string(&*token::get_name(id)) {
                                                                                                                                                                   ^~~~~~~~~~~~~~~
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:203:35: 203:50 help: run `rustc --explain E0425` to see a detailed explanation
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:217:21: 217:36 error: unresolved name `token::get_name` [E0425]
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:217                     token::get_name(id.name))))
                                                                                                                                                     ^~~~~~~~~~~~~~~
note: in expansion of format_args!
<std macros>:2:26: 2:57 note: expansion site
<std macros>:1:1: 2:61 note: in expansion of format!
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:216:18: 217:46 note: expansion site
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustlex_codegen-0.3.0/src/parser.rs:217:21: 217:36 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 3 previous errors
   Compiling kernlog v0.2.0
Build failed, waiting for other jobs to finish...
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 warning: the trait `core::marker::Sized` is not implemented for the type `Self` [E0277]
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 help: run `rustc --explain E0277` to see a detailed explanation
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: `Self` does not have a constant size known at compile-time
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: this warning results from recent bug fixes and clarifications; it will become a HARD ERROR in the next release. See RFC 1214 for details.
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201:5: 201:64 note: required by `core::result::Result`
/home/steve/.multirust/toolchains/nightly/cargo/registry/src/github.com-0a35038f75765ae4/rustc-serialize-0.3.15/src/serialize.rs:201     fn decode<D: Decoder>(d: &mut D) -> Result<Self, D::Error>;
                                                                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Could not compile `rustlex_codegen`.

To learn more, run the command again with --verbose.
```

The warnings on `serialize` can be fixed by updating it to the latest version.

https://github.com/rust-lang/rust/commit/00a5e66f818ad9d79cc4425f5564c7b07e3213a6 would seem to be related?

**Comment by kstep** [comment]
@raininja As cron-next follows nightly to use some unstable features, it can break from time to time. Try running `cargo update` to update to latest deps and then rebuild.

**Comment by steveklabnik** [comment]
@kstep that doesn't help, `rustlex_codegen` HEAD is just busted at the moment.

**Comment by kstep** [comment]
@steveklabnik thank you for looking into the issue! That's what was on my mind when I advised running `cargo update`.

**Comment by kstep** [comment]
@steveklabnik well, that's the price for using nightly. We should wait a little then for dust to settle.

**Comment by steveklabnik** [comment]
I noticed you're using a fork of rumblebars, the upstream is three commits ahead, but doesn't seem to have fixed it yet.

**Comment by kstep** [comment]
@steveklabnik You are right! Seems like I forgotten to switch back to original repo after my PR was merged. Thanks duty pointing it out!

**Comment by raininja** [comment]
upstream problem. thx for the quick replies.

**Comment by kstep** [comment]
For the history, there are three (sic!) PRs in the [LeoTestard/rustlex](https://github.com/LeoTestard/rustlex) repo with almost identical fixes for nightlies: LeoTestard/rustlex#29, LeoTestard/rustlex#30 and LeoTestard/rustlex#32. Seems like @LeoTestard just unreachable at the moment, or not interested in the project, whatever.

**Comment by kstep** [comment]
I solved it by cloning rustlex repo locally, patching it with any of the patches from the PRs mentioned above and putting the following code to `.cargo/config`:

```toml
paths = ["../rustlex", "../rustlex/codegen"]
```

**Comment by raininja** [comment]
well the https://github.com/nicolas-cherel/rumblebars repo plus the rustlex he pushed works fine
