### ISSUE TITLE
More testing required

### ISSUE THREAD

**Issue by kstep** [systemd-cron/systemd-cron-next#28]
I adopted installation process from @systemd-cron, so it's almost unchanged from end user view point, except you have a build time dependency on Rust+cargo instead of runtime dependency on Python. Now, that I have working package in AUR, and have it running both on my server and my work laptop, I need more widespread testing.

@a-detiste, @dbent, your are welcome to take part in testing, if you you're willing to. Thank you!

**Comment by a-detiste** [comment]
Hi,

It seems that these `cargo`& `rustc` things have finally landed in Debian.

I tried to build it, but only got 3 empty directories.

```
tchet@antec:~/git/systemd-cron-next$ ./configure
tchet@antec:~/git/systemd-cron-next$ make 
mkdir -p /home/tchet/git/systemd-cron-next/out/build
mkdir -p /home/tchet/git/systemd-cron-next/out/build/bin
mkdir -p /home/tchet/git/systemd-cron-next/out/build/man
mkdir -p /home/tchet/git/systemd-cron-next/out/build/units
tchet@antec:~/git/systemd-cron-next$ find out/
out/
out/build
out/build/units
out/build/bin
out/build/man
```

**Comment by a-detiste** [comment]
`make build` does something, mainly downloading dependencies for now

**Comment by a-detiste** [comment]
does that seems ok for a fix ?

```diff
diff --git a/Makefile.in b/Makefile.in
index 4ad0c1d..acb69f1 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -42,7 +42,7 @@ endef
 null :=
 persistent = $(if $(filter $(enable_persistent),yes),persistent,)
 
-all: $(builddir) $(outputs)
+all: build
 
 clean:
        rm -rf $(outdir)
@@ -55,12 +55,12 @@ VERSION: Cargo.toml
 
 dist: $(tarball)
 
-test: all
+test: $(builddir) $(outputs)
        $(foreach manpage,$(out_manuals),\
                man --warnings --encoding=utf8 --local-file $(manpage) 2>&1 > /dev/null${\n})
        cargo test
 
-build: all
+build: $(builddir) $(outputs)
        test -f $(builddir)/bin/systemd-crontab-generator || \
            PREFIX="$(prefix)" RUN_PARTS="$(runparts)" STATE_DIR="$(statedir)" \
            BIN_DIR="$(bindir)" CONF_DIR="$(confdir)" MAN_DIR="$(mandir)" DOC_DIR="$(docdir)" \
```

**Comment by a-detiste** [comment]
This is what is documented in the debugging instruction (`run s-c-g /tmp`), it should fail more gracefuly
on those files in $statedir that can only be read as root.

```
/lib/systemd/system-generators/systemd-crontab-generator /tmp
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 13, message: "Permission denied" } }', src/libcore/result.rs:738
tchet@antec:~/git/systemd-cron-next$ sudo /lib/systemd/system-generators/systemd-crontab-generator /tmp
tchet@antec:~/git/systemd-cron-next$
```

```
systemd-cron-next$ sudo ls /var/spool/cron/crontabs/ -ld
drwx-wx--T 2 root crontab 4096 sep 19 08:21 /var/spool/cron/crontabs/
tchet@antec:~/git/systemd-cron-next$ sudo ls /var/spool/cron/crontabs/ -l
total 12
-rw------- 1 julie crontab 176 déc 12  2014 julie
-rw------- 1 root  crontab   4 sep 14 00:04 root
-rw------- 1 tchet crontab 160 sep 19 08:21 tchet
```

**Comment by a-detiste** [comment]
wow, these executables are huge ... are there some compile flags missing to strip those ?

```
-rwxr-xr-x 1 root root    323 oct 27 23:14 boot_delay
-rwxr-xr-x 1 root root 309360 déc 17 13:53 boot-delay
-rwxr-xr-x 1 root root   1404 oct 27 23:14 mail_on_failure
-rwxr-xr-x 1 root root 371984 déc 17 13:53 mail-on-failure
-rwxr-xr-x 1 root root   1010 oct 27 23:14 remove_stale_stamps
-rwxr-xr-x 1 root root 358128 déc 17 13:53 remove-stale-stamps
```

**Comment by kstep** [comment]
> wow, these executables are huge ... are there some compile flags missing to strip those ?

It's OK, because Rust builds static executables with stdlib bundled into them. I can try to build them without stdlib by trying to use core features only, and it will make binaries very small (like if they we written in C), but I'm not sure I can do it in a nice way.

**Comment by kstep** [comment]
What Rust version does Debian have in repositories? I don't have Debian machine in site, so I can't test it. And it builds on Arch for sure. It uses cargo build script to build units etc, and it needs at least cargo 0.6.0 with install subcommand available.

**Comment by a-detiste** [comment]
> What Rust version does Debian have in repositories?

https://packages.qa.debian.org/r/rustc.html says 1.5.0

https://packages.qa.debian.org/c/cargo.html says 0.6.0

>  it builds on Arch for sure

because the PKBUILD does call `make build` instead of a simple `make`,
it's weird to have a Makefile with a default rule that doesn't do the expected thing

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=systemd-cron-next

**Comment by a-detiste** [comment]
embedded libraires are clearly frowned upon in Debian...
even things like e.g. libhtmlcxx that are by used a single depedency ( lgogdowloader )
does deserve their own package.

and the shared library is there too:
https://packages.debian.org/unstable/libstd-rust-1.5

well that's 65Mb of libraries to run some tiny programs

**Comment by a-detiste** [comment]
There should be spaces between Environment items

`./configure --enable-boot=no` doesn't work

```
déc 17 16:08:16 antec systemd[1]: Reloading.
déc 17 16:08:17 antec systemd[1]: [/run/systemd/generator/cron-8070292452c93d85230f42fb41fd2bc0.service:12] Trailing garbage, ignoring.

cat /run/systemd/generator/cron-8070292452c93d85230f42fb41fd2bc0.service 
[Unit]
Description=[Cron] "56 18 * * * root test -x /etc/cron.daily/popularity-contest && /etc/cron.daily/popularity-contest --crond"
Documentation=man:systemd-crontab-generator(8)
RefuseManualStart=true
RefuseManualStop=true
SourcePath=/etc/cron.d/popularity-contest

[Service]
Type=oneshot
IgnoreSIGPIPE=false
ExecStart=/run/systemd/generator/cron-8070292452c93d85230f42fb41fd2bc0.sh
Environment="PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin""PERSISTENT=true""SHELL=/bin/sh"

tchet@antec:~$ sudo systemctl restart cron.target
Failed to restart cron.target: Unit cron-boot.timer failed to load: No such file or directory.
```

**Comment by kstep** [comment]
I managed to strip down binaries sizes to about half of their original size by compiling them with dynamic linking mode. The price is dependency on libstd-rust. Though I'm not convinced it's good for system service run at the boot: now Rust dependency is build time only, when linked dynamically it will become runtime dependency (on at least libstd). Anyway, does it work for you?

**Comment by kstep** [comment]
Also, it's not totally honest to compare libstd-rust size + size of all compiled executables with python scripts, because you should then include the size of python interpreter and all the python libraries and runtime to make this comparison honest.

**Comment by kstep** [comment]
> This is what is documented in the debugging instruction (run s-c-g /tmp), it should fail more gracefuly
on those files in $statedir that can only be read as root.

This is because it can't open `/dev/kmsg` for logging, not because it can not access statedir.
The generator was built to run by systemd as root, at boot (when only `/dev/kmsg` is available for logging). Maybe it should just use stdout for logging if `/dev/kmsg` is not accessible, though.

**Comment by kstep** [comment]
FYI there's a discussion about Rust programs packaging in Debian: https://m.reddit.com/r/rust/comments/2tnql2/how_rust_applications_and_libraries_fit_into/

**Comment by kstep** [comment]
Seems like I will need not only libstd-rust dependency in Debian, but also have all Rust crates I depend on packaged as a separate deb-packages, according to Debian packaging policy as I understand it.

 IAnd because 1) I cannot bundle dependencies, 2) I cannot link dynamically against other crates I depend on (at least it's nontrivial to do because Rust doesn't have stable ABI, and it's good chance, that even if I manage to link my binaries against other crates in a proper dynamic way, I will have to do the same with dependencies of dependencies, as it will very likely require changes in source codes, so it becomes too complex task for me to accomplish alone), I think I will just drop an idea to package for Debian official repositories. Maybe I'll provide self made binary deb-package, but that's all.

**Comment by a-detiste** [comment]
For some languages (? javascript), people have come up with packages with one usefull line of code...
that doest scale well.

> Maybe I'll provide self made binary deb-package, but that's all.

You can even ship a `debian/` folder in the git three.

> , it's not totally honest to compare libstd-rust size + size of all compiled executables with python scripts, 

I was comparing those in mind with wat they would weight as compiled C program.
An empty C program doesn"t weight 300k

```
echo 'main(){}' | gcc  -x c -
strip a.out
du -b a.out 
4344    a.out
```

If I had will & unlimited time I'd had rewriten systemd-cron in C.

**Comment by a-detiste** [comment]
does that work ?

https://github.com/rust-lang/cargo/issues/759

**Comment by kstep** [comment]
I already tried it (see 5901f7e), doesn't help much, makes binaries smaller by about 100Kb.

**Comment by kstep** [comment]
Sure C is smaller, I don't argue about that. Though C doesn't bundle libc into compiled binary. If I compile empty Rust program with dynamic linking, I get just a little overhead over C:

```rust
fn main(){}
```

```
$ rustc -C prefer-dynamic main.rs
$ ls -lF main
-rwxr-xr-x 1 root root 5788 дек 19 01:54 main*
```

I wouldn't like to start holy wars here. Neither you nor I are going to do it in C, so it's just irrelevant and not practical. The problem is not the language, but the linking model.

**Comment by kstep** [comment]
What if I find some way to build everything with libstd-rust linked dynamically, but leave all crates I depend on bundled up and linked statically? Will it work for you?

**Comment by a-detiste** [comment]
I had hoped that rust would be some magical solution that would provide both the benefits of C (small binaries, no huge runtime) & safe data types. I won't fight over inclusion of this in Debian, like I didn't fought over the inclusion of the `setgid`C wrapper for running crontab.py as non-root either. The better way to fix this in Debian would have been to spun out crontab out of cron.deb and just use that; but I have no control of the cron package and no one want to touch it anyway: it's always the same source tarball from 1993 with a ton of patches; not something more modern like Fedora's cronie.

I was just interresting in reviewing -next a bit to make it better for Arch users & learn new things.
I think there might actually still be a bug for --enable-boot; for the rest it's fine;
you don't need to waste more time on Debian's premature support for rust.
(I see that nothing depends on libstd-rust-1.5 outside of rustc itself)

**Comment by kstep** [comment]
In the end I don't think it's a great issue if all dependent crates will be compiled in statically.
It's the normal Rust way, and besides all these crates are effectively distributes in open source, and given how Rust works, using them is (somewhat) analogous to including C headers.

**Comment by kstep** [comment]
Thank you for your help and ideas very much! I will look into a way to link libstd dynamically, just not for now, as it's too much hustle for little benefit, IMO.
