### ISSUE TITLE
RANDOM_DELAY should translate to RandomizedDelaySec, not AccuracySec

### ISSUE THREAD

**Issue by silverhammermba** [systemd-cron/systemd-cron-next#35]
`AccuracySec` does not randomly stagger timers (see [this long discussion](https://wiki.archlinux.org/index.php?title=Talk:Systemd/Timers&oldid=342227#Parallelization_section_is_confusing)). `RandomizedDelaySec` was recently added to support this feature: systemd/systemd@6f5d799

**Comment by a-detiste** [comment]
I plan to add this on systemd-cron python implentation too
https://github.com/systemd-cron/systemd-cron/issues/45

**Comment by kstep** [comment]
Thank you for pointing it out. I will take care of the issue this Friday.
