### ISSUE TITLE
gentoo ebuild?

### ISSUE THREAD

**Issue by soredake** [systemd-cron/systemd-cron-next#37]

**Comment by kstep** [comment]
I don't use Gentoo, so I don't know how to create ebuilds. If you manage to create an ebuild, I'll be happy to include it into the source tree.

**Comment by mikken** [comment]
No, please don't, they are supposed to be included into repositories, not source tree.

Here is my `systemd-cron-next-1.0.2.ebuild`.

To the author: please notice I had to replace `getent group cron` with `getent group cron > /dev/null && echo cron` in `Makefile.in` because `getent group cron` prints out something like `cron:x:16:username` and it results in install error.

```
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=6

DESCRIPTION="Compatibility layer for crontab-to-systemd timers framework"
HOMEPAGE="https://github.com/systemd-cron/systemd-cron-next"
SRC_URI="https://github.com/systemd-cron/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"
IUSE="minutely quaterly yearly persistent"

DEPEND="dev-lang/rust dev-util/cargo sys-process/cronbase"
RDEPEND=">=sys-apps/systemd-229
        sys-process/cronbase
        sys-apps/debianutils
        !sys-process/systemd-cron"

src_prepare()
{
        sed -i -e 's/getent group cron/getent group cron >\/dev\/null \&\& echo cron/' Makefile.in || die
        eapply_user
}

src_configure() {
        ./configure --prefix=/usr --confdir=/etc \
                $(my_use_enable minutely) \
                $(my_use_enable quaterly) \
                $(my_use_enable yearly) \
                $(my_use_enable persistent)
}

src_install() {
        # To remove trailing "/"
        emake DESTDIR="${PORTAGE_BUILDDIR}/image" install
}
```

If you use it don't forget to also update ebuild for `virtual/cron`:
`cron-0-r1.ebuild`

```
# Copyright 1999-2015 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

EAPI=4

DESCRIPTION="Virtual for cron"
HOMEPAGE=""
SRC_URI=""

LICENSE=""
SLOT="0"
KEYWORDS="alpha amd64 arm hppa ia64 m68k ~mips ppc ppc64 s390 sh sparc x86 ~sparc-fbsd ~x86-fbsd"
IUSE=""

DEPEND=""
RDEPEND="|| ( sys-process/cronie
                sys-process/vixie-cron
                sys-process/bcron
                sys-process/dcron
                sys-process/fcron
                sys-process/systemd-cron
                sys-process/systemd-cron-next )"
```

**Comment by mikken** [comment]
Also notice README talks about `--runpaths` option for `./configure` but it's actually `--runparts`.

**Comment by a-detiste** [comment]
> Also notice README talks about --runpaths option for ./configure but it's actually --runparts.

I can fix this little glitch, but have no time to review this bug right now.

**Comment by kstep** [comment]
@a-detiste, thank you for the fix despite lack of time!

**Comment by cjmayo** [comment]
ebuild needs to work with FEATURES="network-sandbox" which usually means using the cargo eclass
https://wiki.gentoo.org/wiki/Project:Rust
requiring all the crates to be defined in the ebuild, but this is easy using cargo-ebuild:
https://github.com/cardoe/cargo-ebuild
ebuild name becomes systemd-crontab-generator to match its own crate.

My attempt, using the getent sed above but with fewer flags to be closer to a drop in for systemd-cron:
https://github.com/cjmayo/gentoo/tree/systemd-crontab-generator/sys-process/systemd-crontab-generator

N.B. issue with USE="-cron-boot" #41

**Comment by kstep** [comment]
So, do you have any issues with ebuilds? Are any changes required on systemd-cron-next's side? If not, I'd rather close the issue.

**Comment by mikken** [comment]
Nope, no problems.
