### ISSUE TITLE
Timezone support?

### ISSUE THREAD

**Issue by passcod** [systemd-cron/systemd-cron-next#45]
Crontabs can be [configured with `CRON_TZ`](https://serverfault.com/questions/848829/how-to-use-timezone-with-cron-tab) to specify the tab's timezone. This is so far the only thing keeping me still on crons rather than systemd timers. Could this project support timezones?

**Comment by kstep** [comment]
According to https://www.freedesktop.org/software/systemd/man/systemd.time.html, it is not possible to set the arbitrary timezone in timer unit:

> When parsing, systemd will accept a similar syntax, but expects no timezone specification, unless it is given as the literal string "UTC" (for the UTC timezone) or is specified to be the locally configured timezone. **Other timezones than the local and UTC are not supported.**

So it's technically possible to implement it for any TZ. We can, although, accept UTC or local TZ as a possible CRON_TZ values to append to `OnCalendar` parameter. Will it help you?

**Comment by kstep** [comment]
Another option would be to adjust datetimes according to CRON_TZ option (if present) to UTC and set all timers in UTC explicitly, but won't work for daylight savings time changes.

**Comment by passcod** [comment]
For the latter option, which would be the useful one for me (servers are in UTC, but need to run some crons in NZ time): would it be possible to parse the relevant timezone file and set a timer at the DST time change boundaries to regenerate the crontab?

**Comment by kstep** [comment]
Ok, seems interesting stuff to implement. I will look into it in the next several days.

**Comment by kondor6c** [comment]
Is this still and issue? The man page seems to reflect support for timezones.
> Timezone can be specified as the literal string "UTC", or the local timezone, similar to the supported syntax of timestamps (see above), or the timezone in the IANA timezone database format (also see above).

**Comment by passcod** [comment]
systemd does seem to support timezones as wanted, that's good news! I don't think this tools supports writing timezones into generated files though

**Comment by kondor6c** [comment]
sounds good :-) just wanted to update the thread of this open issue. With upstream having support maybe this might be a good first issue?
